Repository GSG-G11/Quizzer, pull requests merged in 2022-05, with the labels that each got.

#70 update leaderboard data
  __test__/student.test.ts
  server/controllers/index.ts
  server/controllers/student/index.ts
  server/controllers/student/update-leaderboard.ts
  server/database/config/build/fakeData.sql
  server/database/queries/index.ts
  server/database/queries/student/index.ts
  server/database/queries/student/update-leaderboard-query.ts
  server/routes/student/index.ts
  server/utils/index.ts
  server/utils/validation/index.ts
  server/utils/validation/update-leaderboard-schema.ts
Labels: Awaiting Review, Back-End

#83 Enhancements
  client/src/App/index.css
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
Labels: Awaiting Review, Back-End, Front-End

#86 Create Formik Generic Form
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Components/FormUI/Form/index.tsx
  client/src/Components/FormUI/Input/index.tsx
  client/src/Components/FormUI/Submit/index.tsx
  client/src/Components/FormUI/index.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End

#88 fix some styles settings
  client/src/App/index.css
  client/src/theme.ts
Labels: Awaiting Review, Front-End

#90 Create SnackBar Component
  client/src/Components/FormUI/Form/index.tsx
  client/src/Components/FormUI/Input/index.tsx
  client/src/Components/FormUI/Submit/index.tsx
  client/src/Components/SnackBar/index.tsx
  client/src/Hooks/index.ts
  client/src/Hooks/snackbar-hook.ts
  client/src/mui.ts
  package-lock.json
Labels: Awaiting Review, Front-End

#92 feat(auth): disable react devtools when in production (#85)
  client/package-lock.json
  client/package.json
  client/src/index.tsx
Labels: Awaiting Review

#91 add Navbar component
  client/src/App/index.tsx
  client/src/Components/Navbar/Interfaces.ts
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/Navbar.module.css
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Components/index.ts
  client/src/Hooks/useAuth.ts
  client/src/index.tsx
  client/src/utils.ts
Labels: Awaiting Review, Front-End

#95 Private Quiz code Form
  client/package-lock.json
  client/package.json
  client/src/App/index.tsx
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Student/PrivateQuizForm/index.tsx
  client/src/Components/Student/index.ts
  client/src/Components/index.ts
  client/src/Hooks/index.ts
  client/src/Hooks/use-auth.ts
  client/src/Pages/Student/Private.tsx
  client/src/Validation/index.ts
  client/src/Validation/search-for-private-quiz-schema.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End

#100 Added Protected Routes And Created AuthProvider
  client/src/App/index.tsx
  client/src/Auth/RequireAuth.tsx
  client/src/Auth/auth.tsx
  client/src/Auth/interfaces.ts
  client/src/Hooks/use-auth.ts
  client/src/Utils/index.ts
  client/src/index.tsx
Labels: Awaiting Review, Front-End

#102 Fix RequireAuth
  client/src/App/index.tsx
  client/src/Auth/RequireAuth.tsx
  client/src/Auth/auth.tsx
  client/src/Auth/interfaces.ts
  client/src/Components/Navbar/MenuList.tsx
Labels: Awaiting Review, Priority-01, Front-End

#106 add public quizzes page
  client/src/App/index.tsx
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Pages/Student/Public.tsx
  client/src/Pages/Student/index.ts
  client/src/Pages/Student/public-quizzes/categories.ts
  client/src/Pages/Student/public-quizzes/index.tsx
  client/src/Pages/Student/public-quizzes/interfaces.ts
  client/src/Pages/index.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End, Priority-05

#104 Create Leaderboard Page
  client/.eslintrc.json
  client/src/App/index.tsx
  client/src/Auth/auth.tsx
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Components/Student/QuizResult/QuizResult.module.css
  client/src/Pages/Student/Leaderboard.tsx
  client/src/Pages/Student/Leaderboard/Leaderboard.module.css
  client/src/Pages/Student/Leaderboard/index.tsx
  client/src/Pages/Student/QuizDetails/index.tsx
  client/src/Pages/Student/index.ts
  client/src/Pages/Student/public-quizzes/index.tsx
  client/src/Pages/index.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End, Priority-06

#101 Create role modal
  client/package-lock.json
  client/src/App/index.tsx
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Components/RoleModal/index.tsx
  client/src/Components/index.ts
  client/src/mui.ts
  client/src/typings/declaration.d.ts
  package-lock.json
Labels: Awaiting Review, Front-End, Priority-04

#109 Created 'Create Quiz Page'
  client/package-lock.json
  client/src/App/index.css
  client/src/App/index.tsx
  client/src/Auth/RequireAuth.tsx
  client/src/Auth/auth.tsx
  client/src/Components/FormUI/Form/index.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Components/Teacher/CreateQuizForm.tsx
  client/src/Components/Teacher/CreateQuizForm/CreateQuizForm.module.css
  client/src/Components/Teacher/CreateQuizForm/index.tsx
  client/src/Components/Teacher/Question/Question.module.css
  client/src/Components/Teacher/Question/index.tsx
  client/src/Components/Teacher/QuestionFormWrapper/QuestionForm.module.css
  client/src/Components/Teacher/QuestionFormWrapper/index.tsx
  client/src/Components/Teacher/index.ts
  client/src/Components/index.ts
  client/src/Pages/Teacher/CreateQuiz.tsx
  client/src/Pages/Teacher/CreateQuiz/index.tsx
  client/src/Pages/Teacher/index.ts
  client/src/Pages/index.ts
  client/src/Validation/create-quiz-schema.ts
  client/src/Validation/index.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End

#110 Create landing page
  client/src/App/index.tsx
  client/src/Assets/landing.png
  client/src/Pages/Landing/Landing.module.css
  client/src/Pages/Landing/Landing.tsx
  client/src/Pages/Landing/index.tsx
  client/src/mui.ts
Labels: Awaiting Review, Front-End

#112 feat: add create quiz nav button (#76)
  client/src/App/index.css
  client/src/Auth/auth.tsx
  client/src/Components/Navbar/Navbar.module.css
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Navbar/index.tsx
Labels: Awaiting Review, Front-End

#114 Make Landing Page Responsive
  client/src/Pages/Landing/Landing.module.css
  client/src/Pages/Landing/index.tsx
Labels: Awaiting Review, enhancement, Front-End

#117 Add user bio and avatar for token
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
Labels: Awaiting Review, Back-End

#119 Create Access User Components (Login and Signup)
  client/.env.example
  client/package-lock.json
  client/public/env.js
  client/public/index.html
  client/src/App/index.tsx
  client/src/Assets/spinner.gif
  client/src/Auth/auth.tsx
  client/src/Auth/interfaces.ts
  client/src/Components/AccessUser/AccessUser.module.css
  client/src/Components/AccessUser/Interfaces.tsx
  client/src/Components/AccessUser/Login.tsx
  client/src/Components/AccessUser/Signup.tsx
  client/src/Components/AccessUser/index.tsx
  client/src/Components/index.ts
  client/src/Pages/Landing/index.tsx
  client/src/Validation/index.ts
  client/src/Validation/login-schema.ts
  client/src/Validation/signup-schema.ts
  client/src/index.tsx
  client/src/mui.ts
  client/src/typings/declaration.d.ts
Labels: Awaiting Review, Priority-01, Front-End

#121 Continue With Google
  client/package-lock.json
  client/package.json
  client/src/Auth/interfaces.ts
  client/src/Components/AccessUser/Interfaces.tsx
  client/src/Components/AccessUser/Login.tsx
  client/src/Components/AccessUser/Signup.tsx
  client/src/Firebase/config.ts
Labels: Awaiting Review, Priority-02, Front-End

#115 Create teacher quizzes
  client/src/App/index.tsx
  client/src/Contexts/Quizzes/interfaces.ts
  client/src/Contexts/Quizzes/quizzesContext.tsx
  client/src/Hooks/index.ts
  client/src/Hooks/use-quizzes.ts
  client/src/Pages/Teacher/Quizzes.tsx
  client/src/Pages/Teacher/Quizzes/QuizDeleteModal.tsx
  client/src/Pages/Teacher/Quizzes/Quizzes.module.css
  client/src/Pages/Teacher/Quizzes/QuizzesTable.tsx
  client/src/Pages/Teacher/Quizzes/TableContent.tsx
  client/src/Pages/Teacher/Quizzes/TableHeader.tsx
  client/src/Pages/Teacher/Quizzes/index.tsx
  client/src/Pages/Teacher/Quizzes/interfaces.ts
  client/src/Pages/Teacher/index.ts
  client/src/Pages/index.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End

#120 Attend Quiz Page
  client/package-lock.json
  client/package.json
  client/src/App/index.tsx
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Student/QuestionCard/Question.tsx
  client/src/Components/Student/QuestionCard/index.tsx
  client/src/Components/Student/QuizCard.tsx
  client/src/Components/Student/QuizResult/QuizResult.module.css
  client/src/Components/Student/index.ts
  client/src/Components/index.ts
  client/src/Hooks/index.ts
  client/src/Hooks/use-blocker.ts
  client/src/Pages/Student/Quiz-result/index.tsx
  client/src/Pages/Student/Quiz.tsx
  client/src/Pages/Student/Quiz/Quiz.module.css
  client/src/Pages/Student/Quiz/index.tsx
  client/src/Pages/Student/Quiz/interfaces.ts
  client/src/Pages/Student/QuizDetails/index.tsx
  client/src/Pages/Student/index.ts
  client/src/Pages/Student/public-quizzes/index.tsx
  client/src/Pages/Teacher/TeacherProfile/TeacherInfo.tsx
  client/src/Pages/index.ts
  client/src/Utils/index.ts
  client/src/index.tsx
  client/src/mui.ts
  server/validation/update-leaderboard-schema.ts
Labels: Awaiting Review, Front-End

#126 124 enrolled students page
  client/src/App/index.tsx
  client/src/Hooks/index.ts
  client/src/Pages/Teacher/EnrolledStudents/index.tsx
  client/src/Pages/Teacher/QuizDetails.tsx
  client/src/Pages/Teacher/index.ts
  client/src/Pages/index.ts
  client/src/Utils/index.ts
Labels: Awaiting Review, Front-End

#127 add enrolled students page
  client/src/Pages/Student/Quiz-result/index.tsx
  client/src/Pages/Student/Quiz/index.tsx
  client/src/Pages/Student/public-quizzes/categories.ts
  client/src/Pages/Teacher/EnrolledStudents/index.tsx
  server/validation/update-leaderboard-schema.ts
Labels: Awaiting Review

#128 fix: user can navigate back to quiz after leaving quiz page
  client/src/Pages/Student/Quiz/index.tsx
Labels: Awaiting Review

#130 Verify User Email
  client/src/Auth/auth.tsx
  client/src/Auth/interfaces.ts
  client/src/Components/Navbar/index.tsx
  client/src/Components/Teacher/QuestionForm.tsx
  client/src/Pages/Student/Profile.tsx
  client/src/Pages/Teacher/Profile.tsx
  client/src/Pages/Teacher/TeacherProfile/EditTeacherProfileModal.tsx
  server/controllers/auth/index.ts
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
  server/controllers/auth/verify-account.ts
  server/controllers/index.ts
  server/database/build/init.sql
  server/queries/auth/create-hash.ts
  server/queries/auth/delete-hash.ts
  server/queries/auth/index.ts
  server/queries/auth/verify-account.ts
  server/queries/index.ts
  server/routes/auth/index.ts
Labels: Awaiting Review, Back-End, Front-End

#133 Refactor and fix bugs
  client/src/App/index.tsx
  client/src/Pages/Error/Error.module.css
  client/src/Pages/Error/index.tsx
  client/src/Pages/Student/Quiz/Quiz.module.css
  client/src/Pages/Student/Quiz/index.tsx
  client/src/Pages/Teacher/CreateQuiz/CreateQuiz.module.css
  client/src/Pages/Teacher/CreateQuiz/index.tsx
  client/src/Pages/Teacher/Quizzes/TableContent.tsx
  client/src/Pages/index.ts
  client/src/Utils/index.ts
  client/src/Validation/create-quiz-schema.ts
  client/src/Validation/edit-teacher-profile-schema.ts
  client/src/Validation/login-schema.ts
  client/src/Validation/search-for-private-quiz-schema.ts
  client/src/Validation/signup-schema.ts
  server/app.ts
  server/controllers/teacher/edit-profile.ts
  server/queries/teacher/edit-profile.ts
  server/validation/add-quiz-schema.ts
  server/validation/add-score-schema.ts
  server/validation/edit-teacher-profile-schema.ts
  server/validation/quiz-id-schema.ts
  server/validation/signup-schema.ts
  server/validation/update-leaderboard-schema.ts
Labels: Awaiting Review

#132 Create student profile
  __test__/student.test.ts
  client/src/App/index.tsx
  client/src/Components/Navbar/MenuList.tsx
  client/src/Pages/Student/StudentProfile/EditStudentProfileModal.tsx
  client/src/Pages/Student/StudentProfile/StudentInfo.tsx
  client/src/Pages/Student/StudentProfile/StudentProfile.module.css
  client/src/Pages/Student/StudentProfile/StudentQuizzes.tsx
  client/src/Pages/Student/StudentProfile/index.tsx
  client/src/Pages/Student/index.ts
  client/src/Pages/Teacher/EnrolledStudents/index.tsx
  client/src/Pages/index.ts
  client/src/Validation/edit-user-profile-schema.ts
  client/src/Validation/index.ts
  server/controllers/index.ts
  server/controllers/student/edit-student-profile.ts
  server/controllers/student/get-student-profile.ts
  server/controllers/student/index.ts
  server/queries/index.ts
  server/queries/student/edit-student-profile.ts
  server/queries/student/get-student-profile.ts
  server/queries/student/index.ts
  server/routes/student/index.ts
  server/utils/index.ts
  server/utils/models/index.ts
  server/utils/models/student-profile.edited.ts
  server/utils/models/student-quizzes-modal.ts
  server/validation/edit-user-profile-schema.ts
  server/validation/index.ts
Labels: Awaiting Review, Back-End, Front-End

#137 enhancements
  .env.example
  .gitignore
  client/.env.example
  client/.gitignore
  client/package.json
  client/src/App/index.tsx
  client/src/Auth/auth.tsx
  client/src/Auth/interfaces.ts
  client/src/Components/AccessUser/index.tsx
  client/src/Components/Landing/AuthForm.tsx
  client/src/Components/Landing/RoleModal.tsx
  client/src/Components/Student/PrivateQuizForm/index.tsx
  client/src/Pages/Student/Leaderboard/index.tsx
  client/src/Pages/Student/PublicQuizzes/categories.ts
  client/src/Pages/Student/PublicQuizzes/index.tsx
  client/src/Pages/Student/PublicQuizzes/interfaces.ts
  client/src/Pages/Student/QuizDetails/index.tsx
  client/src/Pages/Student/QuizResult/index.tsx
  client/src/Pages/Student/index.ts
  client/src/Pages/Student/public-quizzes/index.tsx
  client/src/index.tsx
  client/src/mui.ts
  package-lock.json
  package.json
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
  server/controllers/auth/verify-account.ts
  server/controllers/teacher/edit-profile.ts
Labels: Awaiting Review, enhancement, Priority-01, Front-End

#143 131 fix quiz page crash on reload
  client/src/App/index.tsx
  client/src/Auth/auth.tsx
  client/src/Components/AccessUser/Interfaces.tsx
  client/src/Components/AccessUser/index.tsx
  client/src/Components/Navbar/Interfaces.ts
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Components/Student/QuestionCard/Question.tsx
  client/src/Components/Student/Quiz-Page/QuestionCard/QuestionInput.tsx
  client/src/Components/Student/Quiz-Page/QuestionCard/index.tsx
  client/src/Components/Student/Quiz-Page/Questions/TabPanel.tsx
  client/src/Components/Student/Quiz-Page/Questions/index.tsx
  client/src/Components/Student/index.ts
  client/src/Components/index.ts
  client/src/Pages/Landing/index.tsx
  client/src/Pages/Student/PublicQuizzes/index.tsx
  client/src/Pages/Student/Quiz/Quiz.module.css
  client/src/Pages/Student/Quiz/index.tsx
  client/src/Pages/Student/Quiz/interfaces.ts
  client/src/Pages/Student/QuizDetails/index.tsx
  client/src/Pages/Student/QuizResult/index.tsx
  client/src/Pages/Student/StudentProfile/index.tsx
  client/src/Pages/Teacher/EnrolledStudents/index.tsx
  client/src/Pages/Teacher/TeacherProfile/index.tsx
  client/src/Utils/index.ts
  client/src/mui.ts
Labels: Awaiting Review, Front-End

#142 `Create new quiz` enhancements
  client/package-lock.json
  client/package.json
  client/src/Components/Student/Quiz-Page/QuestionCard/QuestionInput.tsx
  client/src/Components/Teacher/CreateQuizForm/index.tsx
  client/src/Components/Teacher/Question/MCQ.tsx
  client/src/Components/Teacher/Question/Question.module.css
  client/src/Components/Teacher/Question/ShortAnswer.tsx
  client/src/Components/Teacher/Question/TrueFalse.tsx
  client/src/Components/Teacher/Question/index.tsx
  client/src/Components/Teacher/QuestionFormWrapper/QuestionForm.module.css
  client/src/Components/Teacher/QuestionFormWrapper/index.tsx
  client/src/Hooks/index.ts
  client/src/Hooks/use-snackbar.ts
  client/src/Pages/Student/QuizResult/index.tsx
  client/src/Pages/Teacher/CreateQuiz/index.tsx
  client/src/Pages/Teacher/CreateQuiz/interfaces.ts
  client/src/Pages/Teacher/EnrolledStudents/index.tsx
  client/src/Validation/create-quiz-schema.ts
  client/src/mui.ts
Labels: Awaiting Review, enhancement, Front-End

#145 fix: fixed attend private quiz when not verified issue (#144)
  client/src/Components/Navbar/MenuList.tsx
  client/src/Pages/Student/Quiz/index.tsx
  client/src/Pages/Student/QuizDetails/index.tsx
Labels: Awaiting Review

#146 fix few bugs
  client/package-lock.json
  client/package.json
  client/public/env.js
  client/src/Components/Navbar/MenuList.tsx
  client/src/Components/Navbar/Navbar.module.css
  client/src/Components/Navbar/NavbarActions.tsx
  client/src/Components/Navbar/index.tsx
  client/src/Pages/Student/QuizDetails/index.tsx
  client/src/Utils/index.ts
Labels: Awaiting Review

#147 refactor:
  client/public/index.html
  client/src/Components/Navbar/index.tsx
  client/src/Components/Skeleton/EnrolledStudents.tsx
  client/src/Components/Skeleton/index.ts
  client/src/Components/index.ts
  client/src/Pages/Student/Quiz/index.tsx
  client/src/Pages/Student/QuizResult/index.tsx
  client/src/Pages/Teacher/EnrolledStudents/index.tsx
Labels: Awaiting Review
