Repository GSG-G11/Quizzer, pull requests merged in 2022-04, with the labels that each got.

#18 add database configuration setup files
  client/package-lock.json
  package-lock.json
  package.json
  server/database/config/build/fakeData.sql
  server/database/config/build/index.ts
  server/database/config/build/init.sql
  server/database/config/config.sql
  server/database/config/connections.ts
Labels: Awaiting Review, Back-End

#20 create error handler
  server/errors/custom-error.ts
  server/errors/index.ts
Labels: Awaiting Review, Back-End

#19 Create custom theme for material UI
  .env.example
  client/package-lock.json
  client/src/App/index.jsx
  client/src/mui.js
  client/src/theme.js
  package-lock.json
Labels: Awaiting Review, Front-End

#28 27 set up jest config with typescript
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: Awaiting Review, Back-End

#33 26 logout route
  __test__/auth.test.ts
  server/controllers/auth/index.ts
  server/controllers/auth/logout.ts
  server/controllers/index.ts
  server/routes/auth/index.ts
Labels: Awaiting Review, Back-End

#35 sign user up
  .eslintrc.json
  __test__/auth.test.ts
  __test__/index.test.ts
  package-lock.json
  package.json
  server/controllers/auth/index.ts
  server/controllers/auth/signup.ts
  server/controllers/index.ts
  server/database/config/build/fakeData.sql
  server/database/config/build/init.sql
  server/database/queries/auth/check-email-taken.ts
  server/database/queries/auth/index.ts
  server/database/queries/auth/signup-queries.ts
  server/database/queries/index.ts
  server/interfaces/checkable.ts
  server/interfaces/index.ts
  server/interfaces/user.ts
  server/middlewares/auth/index.ts
  server/routes/auth/index.ts
  server/utils/index.ts
  server/utils/jwt/index.ts
  server/utils/jwt/sign-token.ts
  server/utils/jwt/verify-token.ts
  server/utils/models/index.ts
  server/utils/models/signup-models.ts
  server/utils/validation/index.ts
  server/utils/validation/signup-schema.ts
Labels: Awaiting Review

#40 Create login route
  __test__/auth.test.ts
  package-lock.json
  server/controllers/auth/index.ts
  server/controllers/auth/login.ts
  server/controllers/index.ts
  server/routes/auth/index.ts
  server/utils/index.ts
  server/utils/models/index.ts
  server/utils/models/login-models.ts
  server/utils/validation/index.ts
  server/utils/validation/log-in-schema.ts
Labels: Awaiting Review

#39 get quiz route
  __test__/student.test.ts
  server/controllers/index.ts
  server/controllers/student/getQuiz.ts
  server/controllers/student/index.ts
  server/database/queries/index.ts
  server/database/queries/student/getQuiz.ts
  server/database/queries/student/index.ts
  server/routes/student/index.ts
Labels: Awaiting Review, Back-End, Priority-01

#51 update leadboard table schema
  server/database/config/build/fakeData.sql
  server/database/config/build/init.sql
Labels: Back-End, Priority-01, Approved

#41 store user private score and send email
  .env.example
  __test__/student.test.ts
  package-lock.json
  package.json
  server/controllers/index.ts
  server/controllers/student/add-private-quiz-score.ts
  server/controllers/student/check-user-attend-quiz.ts
  server/controllers/student/index.ts
  server/controllers/student/send-email.ts
  server/database/config/build/fakeData.sql
  server/database/config/build/init.sql
  server/database/queries/index.ts
  server/database/queries/student/add-private-quiz-score-query.ts
  server/database/queries/student/check-user-attend-quiz-query.ts
  server/database/queries/student/get-quiz-details-query.ts
  server/database/queries/student/get-student-email-query.ts
  server/database/queries/student/index.ts
  server/interfaces/user-auth.ts
  server/middlewares/auth/check-auth.ts
  server/middlewares/auth/index.ts
  server/middlewares/index.ts
  server/routes/student/index.ts
  server/utils/email-response.ts
  server/utils/index.ts
  server/utils/jwt/verify-token.ts
Labels: Back-End, Approved

#44 Create New Quiz
  .github/workflows/node.js.yml
  __test__/student.test.ts
  __test__/teacher.test.ts
  package-lock.json
  package.json
  server/controllers/index.ts
  server/controllers/teacher/create-new-quiz.ts
  server/controllers/teacher/index.ts
  server/database/queries/index.ts
  server/database/queries/teacher/create-new-quiz-queries.ts
  server/database/queries/teacher/index.ts
  server/routes/teacher/index.ts
  server/utils/index.ts
  server/utils/models/index.ts
  server/utils/models/quiz-models.ts
  server/utils/validation/add-quiz-schema.ts
  server/utils/validation/index.ts
Labels: Awaiting Review, Back-End

#53 get leaderboard data
  __test__/student.test.ts
  server/controllers/index.ts
  server/controllers/student/getLeaderboard.ts
  server/controllers/student/index.ts
  server/database/queries/index.ts
  server/database/queries/student/getLeaderboardQuery.ts
  server/database/queries/student/index.ts
  server/routes/student/index.ts
Labels: Awaiting Review, Back-End, Priority-01

#63 Updata fake data for quiz id
  __test__/student.test.ts
  server/database/config/build/fakeData.sql
Labels: Awaiting Review, Back-End, Priority-01

#62 get user
  __test__/auth.test.ts
  server/controllers/auth/get-user.ts
  server/controllers/auth/index.ts
  server/controllers/index.ts
  server/routes/auth/index.ts
Labels: Awaiting Review, Back-End, Priority-01

#55 Get quiz quistions
  __test__/student.test.ts
  package-lock.json
  server/controllers/index.ts
  server/controllers/student/get-questions.ts
  server/controllers/student/index.ts
  server/database/queries/index.ts
  server/database/queries/student/get-questions-query.ts
  server/database/queries/student/index.ts
  server/routes/student/index.ts
  server/utils/index.ts
  server/utils/models/index.ts
  server/utils/models/questions.ts
  server/utils/validation/index.ts
  server/utils/validation/quiz-id-schema.ts
Labels: Back-End, Request Change

#56 Get quizzes
  __test__/teacher.test.ts
  server/controllers/index.ts
  server/controllers/teacher/get-quizzes.ts
  server/controllers/teacher/index.ts
  server/database/queries/index.ts
  server/database/queries/teacher/get-my-quizzes.ts
  server/database/queries/teacher/index.ts
  server/routes/teacher/index.ts
  server/utils/index.ts
  server/utils/models/index.ts
  server/utils/models/login-models.ts
  server/utils/models/quizzes-models.ts
Labels: Awaiting Review, Back-End

#67 Create LICENSE
  LICENSE
Labels: Awaiting Review, documentation

#58 Delete quiz data
  __test__/teacher.test.ts
  server/controllers/index.ts
  server/controllers/teacher/delete-quiz.ts
  server/controllers/teacher/index.ts
  server/database/queries/index.ts
  server/database/queries/teacher/delete-quiz.ts
  server/database/queries/teacher/index.ts
  server/routes/teacher/index.ts
  server/utils/index.ts
  server/utils/models/index.ts
Labels: Awaiting Review, Back-End

#59 Teacher profile
  __test__/teacher.test.ts
  server/controllers/index.ts
  server/controllers/teacher/get-profile.ts
  server/controllers/teacher/index.ts
  server/database/queries/index.ts
  server/database/queries/teacher/get-profile.ts
  server/database/queries/teacher/index.ts
  server/routes/teacher/index.ts
Labels: Back-End, Approved
